[package]
name = "line-bot-sdk-rust"
version = "0.1.1"
authors = ["nanato12 <admin@nanato12.info>"]
edition = "2018"
description = "LINE Messaging API SDK for Rust"
readme = "README.md"
repository = "https://github.com/nanato12/line-bot-sdk-rust/"
license-file = "LICENSE"
keywords = ["line", "linebot", "line-bot-sdk", "line-messaging-api"]
categories = ["api-bindings"]

[features]
default = []
rocket_support = ["rocket"]

[dependencies]
rocket = { version = "0.4", optional = true }
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0.97"
chrono = "0.4"
bytes = "0.4"
base64 = "0.9.2"
hmac = "0.6.2"
sha2 = "0.7.1"

[dev-dependencies]
dotenv = "0.15.0"
actix-web = "3.3"
actix-rt = "1.0"
