[package]
name = "line-bot-sdk-rust"
version = "0.1.0"
authors = ["nanato12 <admin@nanato12.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0.97"
chrono = "0.4"
bytes = "0.4"
base64 = "0.9.2"
hmac = "0.6.2"
sha2 = "0.7.1"
